#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-em-socksify
Version  : 0.3.1
Release  : 5
URL      : https://rubygems.org/downloads/em-socksify-0.3.1.gem
Source0  : https://rubygems.org/downloads/em-socksify-0.3.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-eventmachine
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core

%description
# Transparent proxy support for any EventMachine protocol
Dealing with SOCKS and HTTP proxies is a pain. EM-Socksify provides a simple ship to setup and negotiation a SOCKS / HTTP connection for any EventMachine protocol.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n em-socksify-0.3.1
gem spec %{SOURCE0} -l --ruby > rubygem-em-socksify.gemspec

%build
gem build rubygem-em-socksify.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
em-socksify-0.3.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/em-socksify-0.3.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/em-socksify.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/lib/em-socksify.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/lib/em-socksify/connect.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/lib/em-socksify/connectify.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/lib/em-socksify/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/lib/em-socksify/socks5.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/lib/em-socksify/socksify.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/lib/em-socksify/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/spec/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/em-socksify-0.3.1/spec/socksify_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/em-socksify-0.3.1.gemspec
